In [4]:
import tkinter as tk
from tkinter import *
import cv2
from PIL import Image, ImageTk
import os
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import threading


In [1]:
emotion_model = Sequential()
emotion_model.add(Conv2D(32, kernel_size=(
    3, 3), activation= "relu", input_shape=(48, 48, 1)))
emotion_model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
emotion_model.add(MaxPooling2D(pool_size=(2, 2)))
emotion_model.add(Dropout(0.25))
emotion_model.add(Conv2D(32, kernel_size=(3, 3), activation='relu'))
emotion_model.add(MaxPooling2D(pool_size=(2, 2)))
emotion_model.add(Dropout(0.25))
emotion_model.add(Flatten())
emotion_model.add(Dense(1024, activation='relu'))
emotion_model.add(Dropout(0.5))
emotion_model.add(Dense(7, activation='softmax'))
emotion_model.load_weights('model.h5')
cv2.ocl.setUseOpenCL(False)


NameError: name 'Sequential' is not defined

In [6]:
emotion_dict = {
    0: "Angry",
    1: "Disgusted",
    2: "Fearful",
    3: "Happy",
    4: "Sad",
    5: "Neutral",
}

In [7]:
global last_frame1
last_frame1 = np.zeros((480, 640, 3), dtype=np.uint8)
global cap1
show_text=[0]
# global frame_number

In [8]:
def show_subject():
    cap1 = cv2.VideoCapture(0) # INTERNAL CAMERA
    print('OPENED?', cap1.isOpened())
    if not cap1.isOpened():
        print('Cant open Camera')
    # global frame_number
    length = int(cap1.get(cv2.CAP_PROP_FRAME_COUNT))
    # frame_number += 1
    cap1.set(3, 640)
    cap1.set(4, 480)
    cap1.set(10, 100)
    print('Length: ', length)
    # print('Frame Number: ', frame_number)
    # if frame_number >= length:
    #     exit()
    # cap1.set(1, frame_number)
    # print("CAP1", cap1)
    while True:
        flag1, frame1 = cap1.read()
        # cv2.imshow('frame', frame1)
        bounding_box = cv2.CascadeClassifier('./data/haarcascade_frontalface_default.xml')
        gray_frame = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
        num_faces = bounding_box.detectMultiScale(gray_frame, scaleFactor= 1.3, minNeighbors = 5)
        print('Bounding Box', bounding_box)
        print('Num Faces', num_faces)
        for(x, y, w, h) in num_faces:
            print(x, y, w, h)
            cv2.rectangle(frame1, (x,y+50), (x+w, y+h+10), (255, 0, 0), 2)
            roi_gray_frame = gray_frame[y:y + h, x:x + w]
            cropped_img = np.expand_dims(np.expand_dims(cv2.resize(roi_gray_frame, (48, 48)), -1), 0)
            prediction = emotion_model.predict(cropped_img)
            maxindex = int(np.argmax(prediction))
            print(cropped_img)
            # PRINT
            print(maxindex)
            if maxindex > 5:
                print('DOES NOT MATCHED!')
            else:
                print(emotion_dict[maxindex])
                cv2.putText(frame1, emotion_dict[maxindex], (x+20, y-60), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255,255), 2, cv2.LINE_AA)
                show_text[0] = maxindex
        # if flag1 is None:
        #     print('Major Error !!')
        # elif flag1:
        #     global last_frame1
        #     last_frame1 = frame1.copy()
        #     pic = cv2.cvtColor(last_frame1, cv2.COLOR_BGR2RGB)
        #     img = Image.fromarray(pic)
            # imgtk = ImageTk.PhotoImage(image = img)
            # lmain.imgtk = imgtk
            # lmain.configure(image = imgtk)
            # root.update()
            # lmain.after(10, show_subject)
        cv2.imshow('Video', frame1)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            exit()
            break


In [9]:
def show_avatar():
    # frame2 = cv2.imread(emoji_detec)
    pass

In [10]:
if __name__ == "__main__":
    # frame_number = 0
    # root = tk.Tk()
    # lmain = tk.Label(master = root, padx = 50, bd=10)
    # lmain2 = tk.Label(master = root, bd=10)
    # lmain3 = tk.Label(master=root, bd=10, fg="#CDCDCD", bg='#121212')
    # lmain.pack(side=LEFT)
    # lmain.place(x=50, y=250)
    # lmain3.pack()
    # lmain3.place(x = 960, y=250)
    # lmain3.pack(side= RIGHT)
    # lmain2.place(x=900, y=350)

    # root.title('Photo to Emoji')
    # root.geometry('1400x700+80+50')
    # root['bg'] = 'black'
    # exitButton = Button(root, text='Quit', fg='red', command=root.destroy
    # , font=('arial', 25, 'bold')).pack(side=BOTTOM)
    # threading.Thread(target=show_subject).start()
    # threading.Thread(target=show_avatar).start()
    # root.mainloop()
    show_subject()

OPENED? True
Length:  -1
Bounding Box <CascadeClassifier 0000021DBC6125F0>
Num Faces [[259 158 196 196]]
259 158 196 196
[[[[184]
   [183]
   [182]
   ...
   [185]
   [188]
   [189]]

  [[182]
   [180]
   [181]
   ...
   [185]
   [190]
   [186]]

  [[180]
   [177]
   [176]
   ...
   [187]
   [188]
   [187]]

  ...

  [[164]
   [163]
   [162]
   ...
   [159]
   [161]
   [162]]

  [[162]
   [163]
   [160]
   ...
   [159]
   [160]
   [160]]

  [[161]
   [159]
   [163]
   ...
   [157]
   [157]
   [155]]]]
6
DOES NOT MATCHED!
Bounding Box <CascadeClassifier 0000021D9347DA10>
Num Faces [[277 158 181 181]]
277 158 181 181
[[[[182]
   [182]
   [175]
   ...
   [190]
   [190]
   [192]]

  [[185]
   [183]
   [171]
   ...
   [192]
   [190]
   [190]]

  [[183]
   [175]
   [164]
   ...
   [189]
   [190]
   [189]]

  ...

  [[154]
   [156]
   [155]
   ...
   [157]
   [159]
   [163]]

  [[154]
   [155]
   [155]
   ...
   [160]
   [160]
   [161]]

  [[155]
   [154]
   [155]
   ...
   [163]
   [160]
   